services:
  - type: web
    name: chatbot-rag
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -b 0.0.0.0:8000 run:app"
    envVars:
      - key: OPENAI_API_KEY
        value: REMOVED

